import Login from "components/Login";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className="container flex flex-col items-center justify-center h-screen w-screen ">
          <Login />
        </div>
      </main>
    </>
  );
}
